spring.application.name=SportSync

server.port=8080


spring.datasource.url = jdbc:mysql://localhost:3306/SportSyncDataB2
spring.datasource.username=root
spring.datasource.password=ahmad321

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

newsapi.key=d4532b0aa6ab44dc94fc05ce22bb9beb




